tours/urls.py
from django.conf.urls import patterns, url

from tours import views


urlpatterns = patterns('',
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/$',
        view=views.MonthView.as_view(),
        name='month',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/print/$',
        view=views.MonthView.as_view(),
        name='month-print',
        kwargs={'print': True},
    ),
    url(
        regex=r'^month/$',
        view=views.MonthView.as_view(),
        name='month-noargs',
    ),
    url(
        regex=r'^tour/(?P<pk>\d+)/edit/$',
        view=views.EditTourView.as_view(),
        name='tour-edit',
    ),
    url(
        regex=r'^tour/(?P<pk>\d+)/delete/$',
        view=views.DeleteTourView.as_view(),
        name='tour-delete',
    ),
    url(
        regex=r'^tour/new/$',
        view=views.CreateTourView.as_view(),
        name='tour-new',
    ),
    url(
        regex=r'^default-tour/(?P<pk>\d+)/edit/$',
        view=views.EditDefaultTourView.as_view(),
        name='defaulttour-edit',
    ),
    url(
        regex=r'^default-tour/(?P<pk>\d+)/delete/$',
        view=views.DeleteDefaultTourView.as_view(),
        name='defaulttour-delete',
    ),
    url(
        regex=r'^default-tour/new/$',
        view=views.CreateDefaultTourView.as_view(),
        name='defaulttour-new',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/initialize/$',
        view=views.InitializeMonthView.as_view(),
        name='initialize-month',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/uninitialize/$',
        view=views.UninitializeMonthView.as_view(),
        name='uninitialize-month',
    ),
    url(
        regex=r'^month/initialize/$',
        view=views.InitializeMonthView.as_view(),
        name='month-initialize-noargs',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/open/$',
        view=views.CreateOpenMonthView.as_view(),
        name='open-month',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/open/edit/$',
        view=views.CreateOpenMonthView.as_view(),
        name='open-month-edit',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/close/$',
        view=views.CloseMonthView.as_view(),
        name='close-month',
    ),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^', include('core.urls', namespace='core', app_name='core')),
    url(r'^tours/', include('tours.urls', namespace='tours', app_name='tours')),
    url(r'^shifts/', include('shifts.urls', namespace='shifts', app_name='shifts')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles', app_name='profiles')),
    url(r'^public/', include('public.urls', namespace='public', app_name='public')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
)

tours/models.py
import calendar
import datetime
import pytz

from django.conf import settings
from django.db import models

from core import utils as core_utils


class TaskQuerySet(models.QuerySet):
    """
    QuerySet for tours and shifts.
    """
    def semester(self, semester=None, year=None):
        """
        Includes only members who are inactive for the given semester and year
        """
        year, semester = core_utils.parse_year_semester(year=year, semester=semester)
        start, end = core_utils.semester_bounds(semester=semester, year=year)

        return self.filter(time__gte=start, time__lte=end)


class Tour(models.Model):
    source_choices_flat = [
        "Information Office",
        "Marshall's Office",
        "Alumni Association",
        "Admissions Office",
        "Visitas",
        "Parents' Weekend",
        "Comp",
        "Other",
    ]

    source_choices = [(i, i) for i in source_choices_flat]

    source = models.CharField(max_length=500, default="Information Office")
    guide = models.ForeignKey('profiles.Person', null=True, blank=True, related_name='tours')
    time = models.DateTimeField()
    notes = models.TextField(max_length=2000, blank=True)
    missed = models.BooleanField(default=False)
    late = models.BooleanField(default=False)
    length = models.IntegerField(max_length=3, default=75, null=True)
    counts_for_requirements = models.BooleanField(default=True)

    # true if tour was made during the initialization process
    default_tour = models.BooleanField(default=False)

    # custom manager
    objects = TaskQuerySet.as_manager()

    def time_local(self):
        return core_utils.localize_time(self.time)

    def is_upcoming(self):
        now = core_utils.now()
        if self.time > now:
            return True
        else:
            return False

    def is_unclaimed(self):
        if self.guide is None:
            return True
        else:
            return False

    @property
    def claim_eligible(self):
        from tours.utils import month_is_open
        now = core_utils.now()

        # check if the month is open
        if not month_is_open(month=self.time.month, year=self.time.year):
            return False

        # month is open, check if the tour is in the future
        return self.time >= now

    def __unicode__(self):
        if self.guide is not None:
            return self.source + ', ' + self.time.astimezone(pytz.timezone(settings.TIME_ZONE)).strftime("%m/%d/%y %H:%M") + ', ' + self.guide.first_name + ' ' + self.guide.last_name
        else:
            return self.source + ', ' + self.time.astimezone(pytz.timezone(settings.TIME_ZONE)).strftime("%m/%d/%y %H:%M") + ', ' + 'Unclaimed'


class DefaultTour(models.Model):
    source = models.CharField(max_length=500, default="Information Office", choices=Tour.source_choices)
    minute = models.IntegerField(max_length=2)
    hour = models.IntegerField(max_length=2)
    day_num = models.IntegerField(max_length=1, choices=list(enumerate(calendar.day_name)))
    notes = models.TextField(max_length=2000, blank=True)
    length = models.IntegerField(max_length=3, default=75)

    @property
    def time(self):
        return datetime.datetime(2000, 1, 1, self.hour, self.minute)

    def __unicode__(self):
        return self.source + ', ' + unicode(calendar.day_name[self.day_num]) + 's ' + datetime.datetime(2000, 1, 1, self.hour, self.minute).strftime("%H:%M")


class OpenMonth(models.Model):
    month = models.IntegerField(max_length=2)
    year = models.IntegerField(max_length=4)
    opens = models.DateTimeField()
    closes = models.DateTimeField()

    def __unicode__(self):
        return u'{} {}, opens {}, closes {}'.format(calendar.month_name[self.month], self.year, self.opens.strftime('%m/%d/%y %h:%M %a'), self.closes.strftime('%m/%d/%y %h:%M %a'))


class InitializedMonth(models.Model):
    month = models.IntegerField(max_length=2)
    year = models.IntegerField(max_length=4)

    def __unicode__(self):
        return u'{} {}'.format(calendar.month_name[self.month], self.year)


class CanceledDay(models.Model):
    date = models.DateField()

tours/views.py
import calendar
from collections import Counter
import datetime
from dateutil.relativedelta import relativedelta

from django.contrib.auth.models import Group
from django.core.urlresolvers import reverse_lazy, reverse
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.views.generic import View, UpdateView, CreateView, DeleteView

from braces.views import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    MultiplePermissionsRequiredMixin,
)

from core.views import BoardOnlyMixin
from core import utils
from profiles.utils import get_person_by_position
from tours.models import Tour, CanceledDay, DefaultTour, InitializedMonth, OpenMonth
from tours.forms import TourForm, DefaultTourForm, ChooseMonthForm, OpenMonthForm
from tours import utils as tours_utils


class MonthView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        if kwargs.get('public'):
            # make sure this user is active
            if not request.user.person.is_active:
                raise PermissionDenied
        else:
            # make sure this is a board member
            try:
                request.user.groups.get(name='Board Members')
            except Group.DoesNotExist:
                raise PermissionDenied

        now = utils.now()
        year = kwargs.get('year')
        month = kwargs.get('month')
        year, month = utils.parse_year_month(year, month)
        months_list = [(num, name) for num, name in enumerate(list(calendar.month_name)) if num != 0]
        date = datetime.date(year, month, 1)
        next_month = date + relativedelta(months=1)
        prev_month = date + relativedelta(months=-1)
        primary_tour_coordinator = get_person_by_position('Tour Coordinator (Primary)', 'Tour Coordinator')

        is_open, date_closes = tours_utils.month_is_open(month=month, year=year, return_tuple=True)

        if is_open:
            public_url = request.build_absolute_uri(unicode(reverse('public:month', kwargs={'year': year, 'month': month})))
        else:
            public_url = None

        open_eligible = tours_utils.open_eligible(month=month, year=year)

        weeks_with_tours = tours_utils.weeks_with_tours(month=month, year=year)

        context = {
            'months_list': months_list,
            'weeks': weeks_with_tours,
            'now': now,
            'month': month,
            'year': year,
            'next_year': (year + 1),
            'prev_year': (year - 1),
            'next_month': next_month,
            'prev_month': prev_month,
            'month_initialized': tours_utils.is_initialized(month=month, year=year),
            'is_open': is_open,
            'date_closes': date_closes,
            'open_eligible': open_eligible,
            'public_url': public_url,
            'primary_tour_coordinator': primary_tour_coordinator,
        }

        if kwargs.get('public'):
            return render(request, 'public/month.html', context)
        elif kwargs.get('print') is True:
            return render(request, 'tours/month_print.html', context)
        else:
            return render(request, 'tours/month.html', context)


class EditTourView(PermissionRequiredMixin, BoardOnlyMixin, UpdateView):
    permission_required = 'tours.change_tour'
    model = Tour
    form_class = TourForm
    template_name = 'tours/tour_form.html'

    def get_success_url(self):
        return reverse_lazy('tours:month', kwargs={'year': self.object.time_local().year, 'month': self.object.time_local().month})


class CreateTourView(PermissionRequiredMixin, BoardOnlyMixin, CreateView):
    permission_required = 'tours.add_tour'
    model = Tour
    form_class = TourForm
    template_name = 'tours/tour_form.html'

    def get_success_url(self):
        return reverse_lazy('tours:month', kwargs={'year': self.object.time_local().year, 'month': self.object.time_local().month})


class DeleteTourView(PermissionRequiredMixin, BoardOnlyMixin, DeleteView):
    permission_required = 'tours.delete_tour'
    model = Tour

    def get_success_url(self):
        return reverse_lazy('tours:month', kwargs={'year': self.object.time_local().year, 'month': self.object.time_local().month})


class EditDefaultTourView(PermissionRequiredMixin, BoardOnlyMixin, UpdateView):
    permission_required = 'tours.change_defaulttour'
    model = DefaultTour
    form_class = DefaultTourForm
    template_name = 'tours/defaulttour_form.html'

    def get_success_url(self):
        return reverse_lazy('core:settings')


class CreateDefaultTourView(PermissionRequiredMixin, BoardOnlyMixin, CreateView):
    permission_required = 'tours.add_defaulttour'
    model = DefaultTour
    form_class = DefaultTourForm
    template_name = 'tours/defaulttour_form.html'

    def get_success_url(self):
        return reverse_lazy('core:settings')


class DeleteDefaultTourView(PermissionRequiredMixin, BoardOnlyMixin, DeleteView):
    permission_required = 'tours.delete_defaulttour'
    model = DefaultTour

    def get_success_url(self):
        return reverse_lazy('core:settings')


class InitializeMonthView(MultiplePermissionsRequiredMixin, BoardOnlyMixin, View):
    permissions = {
        "all": ('tours.add_tour', 'tours.add_canceledday', 'tours.add_initializedmonth',),
        "any": (),
    }

    def get(self, request, *args, **kwargs):
        month = kwargs.get('month')
        year = kwargs.get('year')
        year, month = utils.parse_year_month(year, month, default=None)
        now = utils.now()

        if not month or not year:
            # show choose form
            choose_month_form = ChooseMonthForm()
            return render(request, 'tours/initialize_choose_month.html', {'form': choose_month_form})

        try:
            month = int(month)
            year = int(year)
        except:
            raise Http404

        # make sure this month isn't initialized or out of allowed range
        date_obj = datetime.datetime(year, month, 1)
        current = datetime.datetime(now.year, now.month, 1)
        last_allowed = utils.add_months(current, 12, True)

        # make sure this month isn't initialized or out of allowed range
        if tours_utils.is_initialized(month=month, year=year) or date_obj < current or date_obj > last_allowed:
            raise PermissionDenied

        weeks = calendar.Calendar().monthdays2calendar(year, month)
        return render(request, 'tours/initialize_month.html', {'weeks': weeks, 'month': month, 'year': year})

    def post(self, request, *args, **kwargs):
        month = kwargs.get('month')
        year = kwargs.get('year')
        year, month = utils.parse_year_month(year, month)
        now = utils.now()

        try:
            month = int(month)
            year = int(year)
        except:
            raise Http404

        # make sure this month isn't initialized or out of allowed range
        date_obj = datetime.datetime(year, month, 1)
        current = datetime.datetime(now.year, now.month, 1)
        last_allowed = utils.add_months(current, 12, True)

        # make sure this month isn't initialized or out of allowed range
        if tours_utils.is_initialized(month=month, year=year) or date_obj < current or date_obj > last_allowed:
            raise PermissionDenied

        # process form
        selected_days = request.POST.get('selected_days', None)
        if selected_days is None:
            return HttpResponseBadRequest

        # make a counter of all selected days (i.e., days on which to have tours)
        if selected_days != '':
            selected_days_counter = Counter([int(i) for i in selected_days.split(',')])
        else:
            selected_days_counter = Counter()

        # make a counter of all days in the month
        month_dates_counter = Counter([i for i in calendar.Calendar().itermonthdays(year, month) if i != 0])
        canceled_days_counter = month_dates_counter - selected_days_counter

        for num, times in canceled_days_counter.items():
            date = datetime.date(year, month, num)
            canceled_day = CanceledDay(date=date)
            canceled_day.save()

        # add default tours on non-blacked out days
        default_tours = DefaultTour.objects.all()
        weeks = calendar.Calendar().monthdatescalendar(year, month)
        for week in weeks:
            for date in week:
                if date.month == month and not CanceledDay.objects.filter(date=date):
                    for default_tour in default_tours.filter(day_num=date.weekday):
                        add_tour = Tour.objects.create(
                            source=default_tour.source,
                            time=datetime.datetime(date.year, date.month, date.day, default_tour.hour, default_tour.minute),
                            notes=default_tour.notes,
                            length=default_tour.length,
                            default_tour=True
                        )

        # mark month as initialized
        initialized_month = InitializedMonth.objects.create(month=month, year=year)
        return redirect('tours:month', month=month, year=year)


class UninitializeMonthView(MultiplePermissionsRequiredMixin, BoardOnlyMixin, View):
    permissions = {
        "all": ('tours.delete_canceledday', 'tours.delete_initializedmonth', 'tours.delete_tour',),
        "any": (),
    }

    def get(self, request, *args, **kwargs):
        try:
            month = kwargs.get('month')
            year = kwargs.get('year')
            year, month = utils.parse_year_month(year, month, default=None)
            obj = InitializedMonth.objects.get(month=month, year=year)
        except InitializedMonth.DoesNotExist:
            raise Http404
        return render(request, 'tours/uninitialize_confirm.html', {'month': month, 'year': year})

    def post(self, request, *args, **kwargs):
        try:

templates/tours/defaulttour_form.html
{% extends "base.html" %}
{% load staticfiles crispy_forms_tags core_tags %}

{% block title %} CKS Tour Management: 
{% if object %}
    Edit Default Tour
{% else %}
    New Default Tour
{% endif %}
{% endblock %}

{% block content %}
{% if object %}
    <h1>Edit Default Tour on {{ object.day_num|day_name }} at {{ object.time|date:"g:i A" }}</h1>
{% else %}
    <h1>New Default Tour</h1>
{% endif %}

{% if object and perms.tours.delete_defaulttour %}
<div class="col-md-8">
{% endif %}
    {% crispy form %}
{% if object %}
</div>
{% endif %}

{% if object and perms.tours.delete_defaulttour %}
<div class="col-md-4">
<div class="panel panel-warning">
    <div class="panel-heading">Warning: these actions are irreversible</div>
    <div class="panel-body">
        <a class="btn btn-warning btn-block post-btn" data-action="delete this default tour" href="{% url 'tours:defaulttour-delete' object.pk %}">Delete this default tour</a>
    </div>
</div>
</div>
{% endif %}

{% endblock %}

templates/tours/edit-month.html
{% extends "base.html" %}
{% load staticfiles core_tags %}

{% block title %} CKS Tour Management: {{month|month_name}} {{year}} {% endblock %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static "css/calendar.css" %}" />
    <link rel="stylesheet" href="{% static "css/edit-month.css" %}" />

    <script>
    $(function() {
        $('#submit_btn').click(function(){
            $('form.edit-month').submit();
        });
    })
    </script>

{% endblock %}

{% block content %}
<h1>
    {{month|month_name}} {{year}}
</h1>

<form class="edit-month" method="post">
    {{ formset.management_form }}
    {% csrf_token %}

<table class="month editall">

    <thead>
        <tr>
            <th>Monday</th>
            <th>Tuesday</th>
            <th>Wednesday</th>
            <th>Thursday</th>
            <th>Friday</th>
            <th>Saturday</th>
            <th>Sunday</th>
        </tr>
    </thead>

    <tbody>
        {% for week in weeks %}
            <tr class="week">
            {% for date, day, tours, canceled in week %}
                <td class="day{% if date == now.day and month == now.month and year == now.year %} current{% endif %}{% if canceled %} canceled{% endif %}" data-date="{{ date }}">
                    {% if date > 0 %} <div class="date_num_container"><span class="date_num">{{ date }}</span></div>
                    <div class="other">
                        
                        {% if tours %}
                        <ul class="tours">
                        
                            {% for tour in tours %}
                                <li class="tour{% if tour.is_missed %} missed{% else %}{% if tour.is_late %} late{% endif %}{% endif %}{% if not tour.guide %} unclaimed{% endif %}"><table class="ind_tour"><tr><td>{{ tour.time|date:"g:i" }}</td>
                                <td>
                                    {% with tour.id as id %}
                                        {{ forms_by_id.id }}
                                    {% endwith %}
                                </td>
                                </tr></table></li>
                            {% endfor %}

                        </ul>
                        {% endif %}
                            
                    </div>
                    {% endif %}
                </td>
            {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>
</form>

<div class="row">
    <div class="col-sm-6 key edit-month-key">
        <div class="panel panel-default equal-height">
            <div class="panel-heading">
                <h3 class="panel-title">Key</h3>
            </div>

            <div class="panel-body">
                <table>
                    <tr><td><div class="key-canceled"></div></td><td>No Regular Tours</td></tr>
                    <tr><td><span class="key-unclaimed-edit">12:00</span></td><td>Unclaimed Tour</td></tr>
                    <tr><td><span class="key-missed">12:00</span></td><td>Missed Tour</td></tr>
                    <tr><td><span class="key-late">12:00</span></td><td>Late Tour</td></tr>
                </table>
            </div>
        </div>
    </div>

    <div class="col-sm-6">
        <div class="panel panel-default equal-height">
            <div class="panel-heading">
                <h3 class="panel-title">Actions</h3>
            </div>
            <div class="panel-body">
                <button id="submit_btn" class="btn btn-danger btn-block">Submit</button>
                <a href="{% url 'tours:month' year month %}" class="btn btn-info btn-block">Return</a>
            </div>
        </div>
    </div>

</div><!-- /.row -->
{% endblock %}

templates/tours/initialize_choose_month.html
{% extends "base.html" %}
{% load staticfiles crispy_forms_tags %}

{% block title %} CKS Tour Management: Initialize Month {% endblock %}

{% block content %}
<h1>Choose a Month to Initialize</h1>

<div class="js-choose-month-container">
{% crispy form %}
</div>


<script type="text/javascript">
$('.js-choose-month-container form').on('submit', function(e){
    e.preventDefault();
    $this = $(this);
    year_month_str = $this.find('.js-month').val()
    var url = '/tours/month/' + year_month_str + '/initialize/';
    window.location = url;
    return false;
});
</script>
{% endblock %}

templates/tours/month.html
{% extends "base.html" %}
{% load staticfiles core_tags %}

{% block title %} CKS Tour Management: {{month|month_name}} {{year}} {% endblock %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static "css/calendar.css" %}" />
{% endblock %}

{% block content %}
<h1>
    <a class="circle-container circle-left" href="{% url 'tours:month' prev_month.year prev_month.month %}">
        <div class="circle"><i class="glyphicon glyphicon-chevron-left"></i></div>
    </a>
    {{month|month_name}} {{year}}
    <a class="circle-container circle-right" href="{% url 'tours:month' next_month.year next_month.month %}">
        <div class="circle"><i class="glyphicon glyphicon-chevron-right"></i></div>
    </a>
</h1>

{% if is_open %}
    <div class="alert alert-success">This month is open for claiming tours. It closes {{ date_closes|date:"m/d/y \a\t g:i a" }}<br />
    The public URL for this month is <a href="{{ public_url }}">{{ public_url }}</a>.
    </div>
{% endif %}


        <table class="month">

            <thead>
                <tr>
                    <th>Monday</th>
                    <th>Tuesday</th>
                    <th>Wednesday</th>
                    <th>Thursday</th>
                    <th>Friday</th>
                    <th>Saturday</th>
                    <th>Sunday</th>
                </tr>
            </thead>

            <tbody>
                {% for week in weeks %}
                    <tr class="week">
                    {% for date, day, tours, canceled in week %}
                        <td class="day{% if date == now.day and month == now.month and year == now.year %} current{% endif %}{% if canceled %} canceled{% endif %}" data-date="{{ date }}">
                            {% if date > 0 %} <div class="date_num_container"><span class="date_num">{{ date }}</span></div>
                            <div class="other">
                                
                                {% if tours %}
                                <ul class="tours">
                                
                                    {% for tour in tours %}
                                        <li class="tour{% if tour.missed %} missed{% else %}{% if tour.late %} late{% endif %}{% endif %}{% if not tour.guide %} unclaimed{% endif %}">
                                            {% if perms.tours.change_tour %}<a href="{% url 'tours:tour-edit' pk=tour.pk %}">{% endif %}
                                                <table class="ind_tour"><tr><td>{{ tour.time|date:"g:i" }}</td><td>{% if tour.guide %}{{ tour.guide.first_name|slice:"0:1" }}. {{ tour.guide.last_name }}{% else %}Unclaimed{% endif %}</td></tr></table>
                                            {% if perms.tours.change_tour %}</a>{% endif %}
                                        </li>
                                    {% endfor %}

                                </ul>
                                {% endif %}
                                    
                            </div>
                            {% endif %}
                        </td>
                    {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
<div class="row">
    <div class="col-sm-{% if perms.tours.change_tour or perms.tours.add_initializedmonth %}4{% else %}6{% endif %} key">
        <div class="panel panel-default equal-height">
            <div class="panel-heading">
                <h3 class="panel-title">Key</h3>
            </div>

            <div class="panel-body">
                <table>
                    <tr><td><div class="key-canceled"></div></td><td>No Regular Tours</td></tr>
                    <tr><td><span class="key-unclaimed">abcdefg</span></td><td>Unclaimed Tour</td></tr>
                    <tr><td><span class="key-missed">abcdefg</span></td><td>Missed Tour</td></tr>
                    <tr><td><span class="key-late">abcdefg</span></td><td>Late Tour</td></tr>
                </table>
            </div>
        </div>
    </div>
    {% if perms.tours.change_tour or perms.tours.add_initializedmonth %}
    <div class="col-sm-4">
        <div class="panel panel-default equal-height">
            <div class="panel-heading">
                <h3 class="panel-title">Actions</h3>
            </div>

            <div class="panel-body">
            {% if month_initialized %}
                <a href="{% url 'tours:month-print' year=year month=month %}" class="btn btn-block btn-danger">Print Info Office Tours</a>
            {% endif %}

            {% if perms.tours.add_initializedmonth %}
                {% if not month_initialized %}
                    <a href="{% url 'tours:initialize-month' year month %}" class="btn btn-block btn-danger">Initialize Month</a>
                {% else %}
                    <a href="{% url 'tours:uninitialize-month' year month %}" class="btn btn-block btn-danger">Uninitialize Month</a>
                {% endif %}
            {% endif %}

            {% if open_eligible and perms.tours.add_openmonth and perms.tours.change_openmonth %}
                {% if is_open %}
                    <a href="{% url 'tours:open-month-edit' year month %}" class="btn btn-block btn-danger">Edit Closing Time</a>
                {% else %}
                    <a href="{% url 'tours:open-month' year month %}" class="btn btn-block btn-danger">Open Month</a>
                {% endif %}
            {% endif %}

            {% if is_open and perms.tours.delete_openmonth %}
                <a href="{% url 'tours:close-month' year month %}" class="btn btn-block btn-warning post-btn" data-action="close this month">Close Month Immediately</a>
            {% endif %}
            </div>
        </div>
    </div>
    {% endif %}

    <div class="col-sm-{% if perms.tours.change_tour or perms.tours.add_initializedmonth %}4{% else %}6{% endif %}">
        <div class="panel panel-default equal-height">
            <div class="panel-heading">
                <h3 class="panel-title cal"><a href="{% url 'tours:month' prev_year month %}" class="cal_btn_left"><span class="glyphicon glyphicon-chevron-left"></span></a> {{ year }}<a href="{% url 'tours:month' next_year month %}" class="cal_btn_right"><span class="glyphicon glyphicon-chevron-right"></span></a></h3>
            </div>

            <div class="panel-body">
                <div class="select-month-container">
                    <div class="select-month-row">
                    {% for num, name in months_list %}
                        <a {% if num == month %} class="active "{% endif %}href="{% url 'tours:month' year num %}" class="month-btn">{{ name|slice:":3" }}</a>
                        {% if num|divisibleby:"4" %}
                            </div>{% if num != 12 %}<div class="select-month-row">{% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/tours/tour_form.html
{% extends "base.html" %}
{% load staticfiles crispy_forms_tags %}

{% block title %} CKS Tour Management: 
{% if object %}
    Edit Tour
{% else %}
    New Tour
{% endif %}
{% endblock %}

{% block content %}
{% if object %}
    <h1>Tour on {{ object.time|date:"m/d/y" }} at {{ object.time|date:"g:i A" }}</h1>
{% else %}
    <h1>New Tour</h1>
{% endif %}

{% if object and perms.tours.delete_tour %}
<div class="col-md-7">
{% endif %}
    {% crispy form %}
{% if object %}
</div>
{% endif %}

{% if object and perms.tours.delete_tour %}
<div class="col-md-4 col-md-offset-1">
<div class="panel panel-warning">
    <div class="panel-heading">Warning: these actions are irreversible</div>
    <div class="panel-body">
        <a class="btn btn-warning btn-block post-btn" data-action="delete this tour" href="{% url 'tours:tour-delete' object.pk %}">Delete this tour</a>
    </div>
</div>
</div>
{% endif %}

{% endblock %}

templates/tours/uninitialize_confirm.html
{% extends "base.html" %}
{% load staticfiles core_tags %}

{% block title %} CKS Tour Management: Uninitialize {{month|month_name}} {{year}} {% endblock %}

{% block content %}
<h1>
    Uninitialize {{month|month_name}} {{year}}
</h1>

<div class="panel panel-danger">
        <div class="panel-heading">Warning: this action is irreversible</div>
        <div class="panel-body">
            Unitializing this month will remove all tours created during the initialization process. Are you sure you want to continue?

            <div class="top-bottom-spacing">
            <a class="btn btn-danger post-btn" href="{% url 'tours:uninitialize-month' month=month year=year %}" data-action="uninitialize this month">Yes, uninitialize this month</a>
            <a class="btn btn-info" href="{% url 'tours:month' month=month year=year %}">No, return</a>
            </div>
        </div>
    </div>

{% endblock %}