core/urls.py
from django.conf.urls import patterns, url
from django.views.generic.base import RedirectView

from core import views


urlpatterns = patterns('',
    url(
        regex=r'^$',
        view=views.HomeView.as_view(),
        name='home',
    ),
    url(
        regex=r'^settings/$',
        view=views.SettingsView.as_view(),
        name='settings',
    ),
    url(
        regex=r'^login/$',
        view=views.LoginView.as_view(),
        name='login',
    ),
    url(
        regex=r'^logout/$',
        view=views.LogoutView.as_view(),
        name='logout',
    ),
    url(
        regex=r'^text-response/$',
        view=views.text_response,
        name='text-response',
    ),
)

tours/urls.py
from django.conf.urls import patterns, url

from tours import views


urlpatterns = patterns('',
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/$',
        view=views.MonthView.as_view(),
        name='month',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/print/$',
        view=views.MonthView.as_view(),
        name='month-print',
        kwargs={'print': True},
    ),
    url(
        regex=r'^month/$',
        view=views.MonthView.as_view(),
        name='month-noargs',
    ),
    url(
        regex=r'^tour/(?P<pk>\d+)/edit/$',
        view=views.EditTourView.as_view(),
        name='tour-edit',
    ),
    url(
        regex=r'^tour/(?P<pk>\d+)/delete/$',
        view=views.DeleteTourView.as_view(),
        name='tour-delete',
    ),
    url(
        regex=r'^tour/new/$',
        view=views.CreateTourView.as_view(),
        name='tour-new',
    ),
    url(
        regex=r'^default-tour/(?P<pk>\d+)/edit/$',
        view=views.EditDefaultTourView.as_view(),
        name='defaulttour-edit',
    ),
    url(
        regex=r'^default-tour/(?P<pk>\d+)/delete/$',
        view=views.DeleteDefaultTourView.as_view(),
        name='defaulttour-delete',
    ),
    url(
        regex=r'^default-tour/new/$',
        view=views.CreateDefaultTourView.as_view(),
        name='defaulttour-new',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/initialize/$',
        view=views.InitializeMonthView.as_view(),
        name='initialize-month',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/uninitialize/$',
        view=views.UninitializeMonthView.as_view(),
        name='uninitialize-month',
    ),
    url(
        regex=r'^month/initialize/$',
        view=views.InitializeMonthView.as_view(),
        name='month-initialize-noargs',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/open/$',
        view=views.CreateOpenMonthView.as_view(),
        name='open-month',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/open/edit/$',
        view=views.CreateOpenMonthView.as_view(),
        name='open-month-edit',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/close/$',
        view=views.CloseMonthView.as_view(),
        name='close-month',
    ),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^', include('core.urls', namespace='core', app_name='core')),
    url(r'^tours/', include('tours.urls', namespace='tours', app_name='tours')),
    url(r'^shifts/', include('shifts.urls', namespace='shifts', app_name='shifts')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles', app_name='profiles')),
    url(r'^public/', include('public.urls', namespace='public', app_name='public')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
)

core/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext as _

from core.setting_validators import setting_validators


class Setting(models.Model):
    name = models.CharField(max_length=500)
    value = models.CharField(max_length=500)
    description = models.CharField(max_length=1000, null=True, blank=True)
    time_set = models.DateTimeField()
    order_num = models.IntegerField()

    value_type_choices = ['int', 'float', 'string', 'bool', 'email', 'semester_or_never']
    value_type_choice_tuples = [(i, i) for i in value_type_choices]

    value_type = models.CharField(choices=value_type_choice_tuples, max_length=50)

    def __unicode__(self):
        return u'{}: {}'.format(self.name, self.value)

    def save(self, *args, **kwargs):
        # avoid ciruclar import
        from core.utils import now

        now_obj = now()
        self.time_set = now_obj

        if not self.pk:
            # object is new, just save it
            return super(Setting, self).save(*args, **kwargs)
        else:
            # don't save it, create a new object instead
            Setting.objects.create(name=self.name, value=self.value, description=self.description, order_num=self.order_num, value_type=self.value_type, time_set=now_obj)

    def clean(self):
        value = self.value
        try:
            validation = setting_validators[self.value_type](value)
            if validation['valid'] is True:
                value = validation['value']
            else:
                errors = []
                for error in validation['errors']:
                    errors.append(ValidationError(_(error), code='invalid'))
                raise ValidationError({'value': errors})
        except (IndexError, KeyError):
            raise ValidationError({'value': _('Invalid value.')}, code='invalid')

tours/models.py
import calendar
import datetime
import pytz

from django.conf import settings
from django.db import models

from core import utils as core_utils


class TaskQuerySet(models.QuerySet):
    """
    QuerySet for tours and shifts.
    """
    def semester(self, semester=None, year=None):
        """
        Includes only members who are inactive for the given semester and year
        """
        year, semester = core_utils.parse_year_semester(year=year, semester=semester)
        start, end = core_utils.semester_bounds(semester=semester, year=year)

        return self.filter(time__gte=start, time__lte=end)


class Tour(models.Model):
    source_choices_flat = [
        "Information Office",
        "Marshall's Office",
        "Alumni Association",
        "Admissions Office",
        "Visitas",
        "Parents' Weekend",
        "Comp",
        "Other",
    ]

    source_choices = [(i, i) for i in source_choices_flat]

    source = models.CharField(max_length=500, default="Information Office")
    guide = models.ForeignKey('profiles.Person', null=True, blank=True, related_name='tours')
    time = models.DateTimeField()
    notes = models.TextField(max_length=2000, blank=True)
    missed = models.BooleanField(default=False)
    late = models.BooleanField(default=False)
    length = models.IntegerField(max_length=3, default=75, null=True)
    counts_for_requirements = models.BooleanField(default=True)

    # true if tour was made during the initialization process
    default_tour = models.BooleanField(default=False)

    # custom manager
    objects = TaskQuerySet.as_manager()

    def time_local(self):
        return core_utils.localize_time(self.time)

    def is_upcoming(self):
        now = core_utils.now()
        if self.time > now:
            return True
        else:
            return False

    def is_unclaimed(self):
        if self.guide is None:
            return True
        else:
            return False

    @property
    def claim_eligible(self):
        from tours.utils import month_is_open
        now = core_utils.now()

        # check if the month is open
        if not month_is_open(month=self.time.month, year=self.time.year):
            return False

        # month is open, check if the tour is in the future
        return self.time >= now

    def __unicode__(self):
        if self.guide is not None:
            return self.source + ', ' + self.time.astimezone(pytz.timezone(settings.TIME_ZONE)).strftime("%m/%d/%y %H:%M") + ', ' + self.guide.first_name + ' ' + self.guide.last_name
        else:
            return self.source + ', ' + self.time.astimezone(pytz.timezone(settings.TIME_ZONE)).strftime("%m/%d/%y %H:%M") + ', ' + 'Unclaimed'


class DefaultTour(models.Model):
    source = models.CharField(max_length=500, default="Information Office", choices=Tour.source_choices)
    minute = models.IntegerField(max_length=2)
    hour = models.IntegerField(max_length=2)
    day_num = models.IntegerField(max_length=1, choices=list(enumerate(calendar.day_name)))
    notes = models.TextField(max_length=2000, blank=True)
    length = models.IntegerField(max_length=3, default=75)

    @property
    def time(self):
        return datetime.datetime(2000, 1, 1, self.hour, self.minute)

    def __unicode__(self):
        return self.source + ', ' + unicode(calendar.day_name[self.day_num]) + 's ' + datetime.datetime(2000, 1, 1, self.hour, self.minute).strftime("%H:%M")


class OpenMonth(models.Model):
    month = models.IntegerField(max_length=2)
    year = models.IntegerField(max_length=4)
    opens = models.DateTimeField()
    closes = models.DateTimeField()

    def __unicode__(self):
        return u'{} {}, opens {}, closes {}'.format(calendar.month_name[self.month], self.year, self.opens.strftime('%m/%d/%y %h:%M %a'), self.closes.strftime('%m/%d/%y %h:%M %a'))


class InitializedMonth(models.Model):
    month = models.IntegerField(max_length=2)
    year = models.IntegerField(max_length=4)

    def __unicode__(self):
        return u'{} {}'.format(calendar.month_name[self.month], self.year)


class CanceledDay(models.Model):
    date = models.DateField()

core/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _

from core.models import Setting
from core.setting_validators import setting_validators


class SettingForm(forms.ModelForm):

    def clean_value(self):
        value = self.cleaned_data.get('value')
        try:
            validation = setting_validators[self.instance.type](value)
            if validation['valid'] is True:
                value = validation['value']
            else:
                errors = []
                for error in validation['errors']:
                    errors.append(ValidationError(_(error), code='invalid'))
                raise ValidationError(errors)
        except (IndexError, KeyError):
            raise ValidationError(_('Invalid value.'), code='invalid')

        return value

    class Meta:
        model = Setting
        fields = ('value',)


SettingFormSet = forms.modelformset_factory(Setting, fields=('value',), extra=0)

core/views.py
from django.core.mail import EmailMultiAlternatives
from django.contrib.auth import logout
from django.views.generic import View
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect

from braces.views import (
    PermissionRequiredMixin,
    LoginRequiredMixin,
    GroupRequiredMixin,
)

from core.forms import SettingFormSet
from core.models import Setting
from profiles.models import Person
from profiles.utils import get_email_by_position
from tours.models import DefaultTour


class BoardOnlyMixin(LoginRequiredMixin, GroupRequiredMixin):
    group_required = 'Board Members'


class SettingsView(BoardOnlyMixin, View):
    def get(self, request, *args, **kwargs):
        existing_settings = Setting.objects.raw('SELECT DISTINCT core_setting.id, core_setting.order_num FROM core_setting INNER JOIN (SELECT MAX(id) AS id FROM core_setting GROUP BY name) maxid ON core_setting.id = maxid.id ORDER BY core_setting.order_num ASC')
        settings = Setting.objects.filter(id__in=(x.pk for x in existing_settings)).order_by('order_num')
        formset = SettingFormSet(queryset=settings)
        default_tours = DefaultTour.objects.all().order_by('day_num', 'hour', 'minute')
        return render(request, 'core/settings.html', {'formset': formset, 'default_tours': default_tours})

    def post(self, request, *args, **kwargs):
        if not request.user.has_perm('core.change_setting'):
            raise PermissionDenied
        data = request.POST
        formset = SettingFormSet(data)
        if formset.is_valid():
            formset.save()
            return redirect('core:settings')
        else:
            default_tours = DefaultTour.objects.all().order_by('day_num', 'hour', 'minute')
            return render(request, 'core/settings.html', {'formset': formset, 'default_tours': default_tours})


class HomeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if request.user.person.is_board:
            return redirect('tours:month-noargs')
        else:
            return redirect('public:home')


class LoginView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect("core:home")

        return render(request, 'social_auth/login.html')


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('core:home')


@csrf_exempt
def text_response(request):
    from_email = to_email = get_email_by_position('Secretary', 'Tour Coordinator (Primary)', 'Tour Coordinator')

    text = request.POST.get('Body')
    from_number = request.POST.get('From')

    if text is None or from_number is None:
        raise PermissionDenied

    try:
        person = Person.objects.get(phone=from_number)
        from_ = person.full_name
    except Person.DoesNotExist:
        from_ = from_number

    msg = EmailMultiAlternatives(u'Text Message to CKS Twilio Account', 'Message from {}: {}'.format(from_, text), from_email, [to_email])
    msg.send()

    return render(request, 'core/response.xml', content_type="text/xml")

templates/core/settings.html
{% extends "base.html" %}
{% load staticfiles crispy_forms_tags core_tags %}

{% block title %} CKS Tour Management: Settings {% endblock %}

{% block extrahead %}    
    <link type="text/css" href="{% static "css/settings.css"%}" rel="stylesheet" />
{% endblock %}

{% block content %}
<form method="post">
    <div class="row">
        <div class="col-sm-6">
            <h2 class="center"> Settings </h3>
                {% csrf_token %}
                {{ formset.management_form }}
                {% for error in form.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
                <table class="table table-striped settings-table">
                    <tbody>
                        {% for form in formset %}
                        <tr>
                            <td>
                                <h3 class="settings-header">{{ form.instance.name }}</h3>
                                <span class="settings-description">{{ form.instance.description }}</span>
                            </td>
                            <td>
                                {% if perms.core.change_setting %}
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <div class="alert alert-danger">{{ error }}</div>
                                        {% endfor %}
                                        {{ field }}
                                    {% endfor %}
                                {% else %}
                                    {{ form.instance.value }}
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% if perms.core.change_setting %}
            <div class="btn-container">
                <button type="submit" class="btn btn-danger">Submit</button>
            </div>
            {% endif %}
        </div>
</form>

        <div class="col-sm-6">
            <h2 class="center"> Default Tours </h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Time</th>
                        <th>Day</th>
                        <th>Source</th>
                        <th>Length</th>
                        {% if perms.tours.change_defaulttour %}
                            <th>Edit</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for default_tour in default_tours %}
                        <tr>
                            <td>{{ default_tour.time|date:"g:i A" }}</td>
                            <td>{{ default_tour.day_num|day_name }}</td>
                            <td>{{ default_tour.source }}</td>
                            <td>{{ default_tour.length }}</td>
                            {% if perms.tours.change_defaulttour %}
                                <td>
                                    <a class="edit-btn" href="{% url 'tours:defaulttour-edit' pk=default_tour.pk %}"><span class="glyphicon glyphicon-edit"></span></a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% if perms.tours.add_defaulttour %}
            <div class="add_default_semester_container">
                <a id="add_default_semester_btn" class="btn btn-info" href="{% url 'tours:defaulttour-new' %}"><span class="glyphicon glyphicon-plus"></span> Add</a>
            </div>
            {% endif %}
        </div>
    </div>


{% endblock %}