core/urls.py
from django.conf.urls import patterns, url
from django.views.generic.base import RedirectView

from core import views


urlpatterns = patterns('',
    url(
        regex=r'^$',
        view=views.HomeView.as_view(),
        name='home',
    ),
    url(
        regex=r'^settings/$',
        view=views.SettingsView.as_view(),
        name='settings',
    ),
    url(
        regex=r'^login/$',
        view=views.LoginView.as_view(),
        name='login',
    ),
    url(
        regex=r'^logout/$',
        view=views.LogoutView.as_view(),
        name='logout',
    ),
    url(
        regex=r'^text-response/$',
        view=views.text_response,
        name='text-response',
    ),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^', include('core.urls', namespace='core', app_name='core')),
    url(r'^tours/', include('tours.urls', namespace='tours', app_name='tours')),
    url(r'^shifts/', include('shifts.urls', namespace='shifts', app_name='shifts')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles', app_name='profiles')),
    url(r'^public/', include('public.urls', namespace='public', app_name='public')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
)

profiles/models.py
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField
import vobject

from core import utils as core_utils


class PersonQuerySet(models.QuerySet):
    def inactive(self, semester=None, year=None):
        """
        Includes only members who are inactive for the given semester and year
        """
        if semester is None:
            semester = core_utils.current_semester()
        if year is None:
            year = core_utils.now().year
        else:
            year = int(year)
            semester = semester.lower()

        return self.filter(inactive_semesters__year__exact=year, inactive_semesters__semester=semester)

    def active(self, semester=None, year=None):
        """
        Excludes members who are inactive for the given semester and year
        """
        if semester is None:
            semester = core_utils.current_semester()
        if year is None:
            year = core_utils.now().year
        else:
            year = int(year)

        semester = semester.lower()

        return self.exclude(inactive_semesters__year__exact=year, inactive_semesters__semester=semester)

    def current_members(self, semester=None, year=None):
        if semester is None:
            semester = core_utils.current_semester()
        if year is None:
            year = core_utils.now().year
        else:
            year = int(year)
            semester = semester.lower()

        senior_year, freshman_year = core_utils.class_years(semester=semester, year=year, bookends_only=True)

        kwargs = {}

        if semester == 'fall':
            kwargs['member_since_year__lte'] = year
        else:
            kwargs['member_since_year__lt'] = year

        kwargs['year__lte'] = freshman_year
        kwargs['year__gte'] = senior_year

        return self.filter(**kwargs)


class Person(models.Model):
    user = models.OneToOneField('auth.User', null=True, blank=True)
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    harvard_email = models.EmailField()
    phone = PhoneNumberField()
    year = models.IntegerField(max_length=4)
    notes = models.TextField(max_length=2000, blank=True)

    titles = ['President', 'Vice President', 'Treasurer', 'Secretary', 'Tour Coordinator (Primary)', 'Tour Coordinator', 'Freshman Week Coordinator', 'Other Board Member', 'Regular Member']

    positions_choices = [(i, i) for i in titles]
    position = models.CharField(max_length=50, choices=positions_choices, default='Regular Member')
    site_admin = models.BooleanField(default=False)

    # member since fall of...
    member_since_year = models.IntegerField(max_length=4)

    houses = ('Adams', 'Quincy', 'Lowell', 'Eliot', 'Kirkland', 'Winthrop', 'Mather', 'Leverett', 'Dunster', 'Cabot', 'Pforzheimer', 'Currier', 'Dudley', 'Freshman (Yard)')
    houses_choices = [(house, house) for house in houses]
    house = models.CharField(choices=houses_choices, max_length=50, blank=True, null=True)

    # custom manager
    objects = PersonQuerySet.as_manager()

    def phone_display(self):
        """
        Removes the +1 from the phone number if it exists.
        """
        phone = unicode(self.phone)
        if phone[:2] == '+1':
            return phone[2:]
        else:
            return phone

    def requirements(self, semester=None, year=None):
        """
        Get requirements for a given semester.
        """
        year, semester = core_utils.parse_year_semester(year, semester)

        tours_required = self.tours_required_num(semester, year)
        shifts_required = self.shifts_required_num(semester, year)
        dues_required = core_utils.dues_required(semester=semester, year=year)

        return tours_required, shifts_required, dues_required

    def tours_required_num(self, semester=None, year=None):
        year, semester = core_utils.parse_year_semester(year, semester)

        # start with default
        tours_required = core_utils.get_default_num_tours(semester=semester, year=year)

        # check for override
        try:
            overridden_reqs = self.overridden_requirements.get(semester=semester, year=year)
            tours_required = overridden_reqs.tours_required
        except OverrideRequirement.DoesNotExist:
            pass

        # get number of missed tours
        num_missed = self.tours.semester(semester=semester, year=year).filter(missed=True).count()
        num_extra = num_missed * core_utils.get_setting('Missed Tour Penalty')

        return tours_required + num_extra

    def shifts_required_num(self, semester=None, year=None):
        year, semester = core_utils.parse_year_semester(year, semester)

        # start with default
        shifts_required = core_utils.get_default_num_shifts(semester=semester, year=year)

        # check for override
        try:
            overridden_reqs = self.overridden_requirements.get(semester=semester, year=year)
            shifts_required = overridden_reqs.shifts_required
        except OverrideRequirement.DoesNotExist:
            pass

        # get number of missed shifts
        num_missed = self.shifts.semester(semester=semester, year=year).filter(missed=True).count()
        num_extra = num_missed * core_utils.get_setting('Missed Shift Penalty')

        return shifts_required + num_extra

    def dues_status(self, semester=None, year=None):
        year, semester = core_utils.parse_year_semester(year, semester)
        dues_required = core_utils.dues_required(semester=semester, year=year)

        if dues_required:
            if self.dues_payments.filter(year=year, semester=semester):
                return 'complete'
            else:
                return 'incomplete'
        else:
            return 'not_required'

    def tours_status(self, semester=None, year=None):
        """
        Returns dictionary of form:
        {
            'status': 'complete'|'incomplete'|'projected',
            'num_required': int,
            'num_remaining': int,
            'num_to_sign_up': int,
            'num_extra': int,
            'date_projected': date|None,
            'complete': [],
            'late': [],
            'missed': [],
            'upcoming': [],
            'tours': [],
        }
        """
        year, semester = core_utils.parse_year_semester(year, semester)
        now_obj = core_utils.now()
        semester_tours = self.tours.filter(counts_for_requirements=True).semester(semester=semester, year=year).order_by('time')
        complete = semester_tours.filter(missed=False, time__lte=now_obj)
        late = semester_tours.filter(late=True, missed=False, time__lte=now_obj)
        missed = semester_tours.filter(missed=True, time__lte=now_obj)
        past = semester_tours.filter(time__lt=now_obj)
        upcoming = semester_tours.filter(time__gte=now_obj)

        num_required = self.tours_required_num(semester=semester, year=year)
        num_remaining = num_required - complete.count()
        num_extra = abs(min(num_remaining, 0))
        num_remaining = max(num_remaining, 0)
        num_to_sign_up = max(num_remaining - upcoming.count(), 0)

        # calculate status
        if num_remaining <= 0:
            status = 'complete'
        elif num_remaining <= upcoming.count():
            status = 'projected'
        else:
            status = 'incomplete'

        if status == 'projected':
            completion_obj = upcoming[num_remaining - 1]
            date_projected = completion_obj.time
        else:
            date_projected = None

        return {
            'status': status,
            'num_required': num_required,
            'num_remaining': num_remaining,
            'num_to_sign_up': num_to_sign_up,
            'num_extra': num_extra,
            'date_projected': date_projected,
            'complete': complete,
            'late': late,
            'missed': missed,
            'past': past,
            'upcoming': upcoming,
            'tours': semester_tours,
        }

    def shifts_status(self, semester=None, year=None):
        """
        Returns dictionary of form:
        {
            'status': 'complete'|'incomplete'|'projected',
            'num_required': int,
            'num_remaining': int,
            'num_to_sign_up': int,
            'num_extra': int,
            'date_projected': date|None,
            'complete': [],
            'late': [],
            'missed': [],
            'past': [],
            'upcoming': [],
            'shifts': [],
        }
        """
        year, semester = core_utils.parse_year_semester(year, semester)
        now_obj = core_utils.now()
        semester_shifts = self.shifts.filter(counts_for_requirements=True).semester(semester=semester, year=year).order_by('time')
        complete = semester_shifts.filter(missed=False, time__lte=now_obj)
        late = semester_shifts.filter(late=True, missed=False, time__lte=now_obj)
        missed = semester_shifts.filter(missed=True, time__lte=now_obj)
        past = semester_shifts.filter(time__lt=now_obj)
        upcoming = semester_shifts.filter(time__gte=now_obj)

        num_required = self.shifts_required_num(semester=semester, year=year)
        num_remaining = num_required - complete.count()
        num_extra = abs(min(num_remaining, 0))
        num_remaining = max(num_remaining, 0)
        num_to_sign_up = max(num_remaining - upcoming.count(), 0)

        # calculate status
        if num_remaining <= 0:
            status = 'complete'
        elif num_remaining <= upcoming.count():
            status = 'projected'
        else:
            status = 'incomplete'

        if status == 'projected':
            completion_obj = upcoming[num_remaining - 1]
            date_projected = completion_obj.time
        else:
            date_projected = None

        return {
            'status': status,
            'num_required': num_required,

shifts/models.py
import pytz

from django.db import models

from core import utils as core_utils
from tours.models import TaskQuerySet


class Shift(models.Model):
    source_choices_flat = (
        "TEACH",
        "Parents' Weekend",
        "Visitas",
        "Comp",
        "Arts First",
        "Freshman Week",
        "Other",
    )

    source_choices = [(i, i) for i in source_choices_flat]

    source = models.CharField(max_length=500)
    person = models.ForeignKey('profiles.Person', related_name='shifts', null=True, blank=True)
    time = models.DateTimeField()
    notes = models.TextField(max_length=2000, blank=True)
    missed = models.BooleanField(default=False)
    late = models.BooleanField(default=False)
    length = models.IntegerField(max_length=3, blank=True, null=True)
    counts_for_requirements = models.BooleanField(default=True)

    # custom manager
    objects = TaskQuerySet.as_manager()

    def time_local(self):
        return core_utils.localize_time(self.time)

    def is_missed(self):
        if self.missed:
            return True
        else:
            return False

    def is_late(self):
        if self.late:
            return True
        else:
            return False

    def is_unclaimed(self):
        if self.person is None:
            return True
        else:
            return False

    @property
    def is_upcoming(self):
        now = core_utils.now()
        if self.time > now:
            return True
        else:
            return False

    def __unicode__(self):
        if self.person is not None:
            return self.source + ', ' + self.time.astimezone(pytz.timezone('America/New_York')).strftime("%m/%d/%y %H:%M") + ', ' + self.person.first_name + ' ' + self.person.last_name
        else:
            return self.source + ', ' + self.time.astimezone(pytz.timezone('America/New_York')).strftime("%m/%d/%y %H:%M") + ', ' + 'Unclaimed'

tours/models.py
import calendar
import datetime
import pytz

from django.conf import settings
from django.db import models

from core import utils as core_utils


class TaskQuerySet(models.QuerySet):
    """
    QuerySet for tours and shifts.
    """
    def semester(self, semester=None, year=None):
        """
        Includes only members who are inactive for the given semester and year
        """
        year, semester = core_utils.parse_year_semester(year=year, semester=semester)
        start, end = core_utils.semester_bounds(semester=semester, year=year)

        return self.filter(time__gte=start, time__lte=end)


class Tour(models.Model):
    source_choices_flat = [
        "Information Office",
        "Marshall's Office",
        "Alumni Association",
        "Admissions Office",
        "Visitas",
        "Parents' Weekend",
        "Comp",
        "Other",
    ]

    source_choices = [(i, i) for i in source_choices_flat]

    source = models.CharField(max_length=500, default="Information Office")
    guide = models.ForeignKey('profiles.Person', null=True, blank=True, related_name='tours')
    time = models.DateTimeField()
    notes = models.TextField(max_length=2000, blank=True)
    missed = models.BooleanField(default=False)
    late = models.BooleanField(default=False)
    length = models.IntegerField(max_length=3, default=75, null=True)
    counts_for_requirements = models.BooleanField(default=True)

    # true if tour was made during the initialization process
    default_tour = models.BooleanField(default=False)

    # custom manager
    objects = TaskQuerySet.as_manager()

    def time_local(self):
        return core_utils.localize_time(self.time)

    def is_upcoming(self):
        now = core_utils.now()
        if self.time > now:
            return True
        else:
            return False

    def is_unclaimed(self):
        if self.guide is None:
            return True
        else:
            return False

    @property
    def claim_eligible(self):
        from tours.utils import month_is_open
        now = core_utils.now()

        # check if the month is open
        if not month_is_open(month=self.time.month, year=self.time.year):
            return False

        # month is open, check if the tour is in the future
        return self.time >= now

    def __unicode__(self):
        if self.guide is not None:
            return self.source + ', ' + self.time.astimezone(pytz.timezone(settings.TIME_ZONE)).strftime("%m/%d/%y %H:%M") + ', ' + self.guide.first_name + ' ' + self.guide.last_name
        else:
            return self.source + ', ' + self.time.astimezone(pytz.timezone(settings.TIME_ZONE)).strftime("%m/%d/%y %H:%M") + ', ' + 'Unclaimed'


class DefaultTour(models.Model):
    source = models.CharField(max_length=500, default="Information Office", choices=Tour.source_choices)
    minute = models.IntegerField(max_length=2)
    hour = models.IntegerField(max_length=2)
    day_num = models.IntegerField(max_length=1, choices=list(enumerate(calendar.day_name)))
    notes = models.TextField(max_length=2000, blank=True)
    length = models.IntegerField(max_length=3, default=75)

    @property
    def time(self):
        return datetime.datetime(2000, 1, 1, self.hour, self.minute)

    def __unicode__(self):
        return self.source + ', ' + unicode(calendar.day_name[self.day_num]) + 's ' + datetime.datetime(2000, 1, 1, self.hour, self.minute).strftime("%H:%M")


class OpenMonth(models.Model):
    month = models.IntegerField(max_length=2)
    year = models.IntegerField(max_length=4)
    opens = models.DateTimeField()
    closes = models.DateTimeField()

    def __unicode__(self):
        return u'{} {}, opens {}, closes {}'.format(calendar.month_name[self.month], self.year, self.opens.strftime('%m/%d/%y %h:%M %a'), self.closes.strftime('%m/%d/%y %h:%M %a'))


class InitializedMonth(models.Model):
    month = models.IntegerField(max_length=2)
    year = models.IntegerField(max_length=4)

    def __unicode__(self):
        return u'{} {}'.format(calendar.month_name[self.month], self.year)


class CanceledDay(models.Model):
    date = models.DateField()

templates/base.html
{% load static core_tags selectize_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!--Google Webmaster Tools -->
    <meta name="google-site-verification" content="" />

    <link rel="stylesheet" href="{% static "css/base.css" %}" />

    <link rel="stylesheet" href="{% static "lib/bootstrap/css/bootstrap.css" %}"  />
    <link rel="stylesheet" href="{% static "lib/hint/hint.min.css" %}"  />
    <link rel="shortcut icon" href="{% static 'app/img/favicon.png' %}" />

    <script src="{% static "lib/jquery/jquery-1.9.1.js" %}"></script>
    <script src="{% static "lib/bootstrap/js/bootstrap.min.js" %}"></script>


    <script src="{% static "lib/jquery/jquery-ui-1.10.3.custom.min.js" %}" type="text/javascript"></script>
    <link type="text/css" href="{% static "lib/jquery/jquery-ui-1.10.3.custom.min.css"%}" rel="stylesheet" />

    <script src="{% static "lib/jquery/jquery-ui-timepicker-addon.js" %}" type="text/javascript"></script>
    <link type="text/css" href="{% static "lib/jquery/jquery-ui-timepicker-addon.css"%}" rel="stylesheet" />

    <link rel="stylesheet" href="{% static "lib/selectize/css/selectize.css" %}"  />
    <link rel="stylesheet" href="{% static "lib/selectize/css/selectize.bootstrap3.css" %}"  />
    <script src="{% static "lib/selectize/js/selectize.min.js" %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/roster.css' %}">
    <link rel="stylesheet" href="{% static 'selectize/css/selectize.default.css' %}">
    <link rel="stylesheet" href="{% static "css/calendar.css" %}" />
    <link rel="stylesheet" media="print" href="{% static "css/calendar-print.css" %}" />
    <link rel="stylesheet" href="{% static "css/edit-month.css" %}" />
    <link rel="stylesheet" href="{% static "css/settings.css" %}" />


    {% selectize_tags_media 'css' 'default' %}

    {% block extrahead %}{% endblock %}

    <title>{% block title %}CKS Tour Management{% endblock %}</title>


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body{% if not user.is_authenticated %} class="login"{% endif %}>

{% if user.is_authenticated %}
{% block menu %}
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'core:home' %}"><div class="logo"></div></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">

            <li class="dropdown {% navactive request 'tours:month,tours:month-print,tours:month-noargs,tours:month-initialize,tours:month-initialize-noargs,shifts:month,shifts:month-noargs' %}">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Months <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li class="{% navactive request 'tours:month, tours:month-noargs' %}"><a href="{% url 'tours:month-noargs' %}">View Month (Tours)</a></li>
                <li class="{% navactive request 'shifts:month, shifts:month-noargs' %}"><a href="{% url 'shifts:month-noargs' %}">View Month (Shifts)</a></li>
                  {% if perms.tours.add_initializedmonth %}<li class="{% navactive request 'tours:month-initialize-noargs,tours:month-initialize' %}"><a href="{% url 'tours:month-initialize-noargs' %}">Initialize Month Tours</a></li>{% endif %}
              </ul>
            </li>

              {% if perms.tours.add_tour %}
              <li class="dropdown {% navactive request 'tours:tour-new, tours:tour-edit, tours:tour-delete' %}">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tours <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="{% navactive request 'tours:tour-new' %}"><a href="{% url 'tours:tour-new' %}">New Tour</a></li>
                </ul>
              </li>
              {% endif %}

              {% if perms.shifts.add_shift %}
                <li class="dropdown {% navactive request 'shifts:shift-new, shifts:shift-edit, shifts:shift-delete' %}">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Shifts <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="{% navactive request 'shifts:shift-new' %}"><a href="{% url 'shifts:shift-new' %}">New Shift</a></li>
                </ul>
              </li>
              {% endif %}

              {% if perms.profiles.add_person %}
                <li class="dropdown {% navactive request 'profiles:person-new, profiles:person-edit, profiles:person-delete' %}">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Members <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="{% navactive request 'profiles:person-new' %}"><a href="{% url 'profiles:person-new' %}">New Member</a></li>
                  <li class="{% navactive request 'profiles:person-new-bulk' %}"><a href="{% url 'profiles:person-new-bulk' %}">New Members (Bulk)</a></li>
                </ul>
              </li>
              {% endif %}

              <li class="{% navactive request 'profiles:roster,profiles:roster-noargs,profiles:send-requirements-emails' %}"><a href="{% url 'profiles:roster-noargs' %}">Roster</a></li>

              <li class="{% navactive request 'core:settings' %}"><a href="{% url 'core:settings' %}">Settings</a></li>

              {% if user %}<li><a href="{% url 'core:logout' %}">Logout ({{ user.person.first_name }} {{ user.person.last_name }})</a></li>{% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    {% endblock %}
    {% endif %}

    <div class="container">
      <div class="messages">
      {% for message in messages %}
        <div class="alert alert-warning">{{ message }}</div>
      {% endfor %}
      </div>
      {% block content %}{% endblock %}
    </div><!-- /.container -->

    <script>

function post_request(action, method, input) {
    'use strict';
    var form;
    form = $('<form />', {
        action: action,
        method: method,
        style: 'display: none;'
    });
    form.append("{% csrf_token %}");
    if (typeof input !== 'undefined' && input !== null) {
        $.each(input, function (name, value) {
            $('<input />', {
                type: 'hidden',
                name: name,
                value: value
            }).appendTo(form);
        });
    }
    form.appendTo('body').submit();
}

$('.post-btn').on('click', function(e){
    e.preventDefault();
    var url = $(this).attr('href');
    var action = $(this).data('action');
    var to_confirm = $(this).data('confirm');
    var proceed = false;
    if (to_confirm == 'false' || to_confirm === false)
    {
      proceed = true;
    }
    else
    {
      proceed = confirm('Are you sure you want to ' + action + '?');
    }
    if (proceed == true)
    {
        post_request(url, 'post', {});
    }
});
$(function() {
  $('.selectize').selectize({
        create: false,
    });
  $('.datepicker').datetimepicker({
    ampm: true,
    dateFormat: 'mm/dd/yy',
    timeFormat: 'hh:mm tt',
    stepMinute: 5
  });

  $('.timepicker').timepicker({
    ampm: true,
    timeFormat: 'hh:mm tt',
    stepMinute: 5
  });
});
    </script>

  </body>
</html>

templates/error_base.html
<html>
<head>
<style>
html, body, h1, p
{
	font-family:'Helevtica Neue', 'Helvetica', sans-serif;
	text-align:center;
}
</style>
<title>{% block title %}{% endblock %}</title>
</head>
<body>
<h1>{% block heading %}{% endblock %}</h1>
<p>{% block body %}{% endblock %}</p>
</body>
</html>