profiles/urls.py
from django.conf.urls import patterns, url

from profiles import views


urlpatterns = patterns('',
    url(
        regex=r'^person/(?P<pk>\d+)/edit/$',
        view=views.EditPersonView.as_view(),
        name='person-edit',
    ),
    url(
        regex=r'^person/(?P<pk>\d+)/delete/$',
        view=views.DeletePersonView.as_view(),
        name='person-delete',
    ),
    url(
        regex=r'^person/new/$',
        view=views.CreatePersonView.as_view(),
        name='person-new',
    ),
    url(
        regex=r'^person/bulk-new/$',
        view=views.BulkCreatePersonView.as_view(),
        name='person-new-bulk',
    ),
    url(
        regex=r'^special-requirements/$',
        view=views.UpdateSpecialRequirementsView.as_view(),
        name='special-requirements-update',
    ),
    url(
        regex=r'^person/(?P<pk>\d+)/inactive-semester/new/$',
        view=views.CreateInactiveSemesterView.as_view(),
        name='inactive-semester-new',
    ),
    url(
        regex=r'^inactive-semester/(?P<pk>\d+)/delete/$',
        view=views.DeleteInactiveSemesterView.as_view(),
        name='inactive-semester-delete',
    ),
    url(
        regex=r'^roster/$',
        view=views.RosterView.as_view(),
        name='roster-noargs',
    ),
    url(
        regex=r'^roster/(?P<year>\d{4})/(?P<semester>\w+)/$',
        view=views.RosterView.as_view(),
        name='roster',
    ),
    url(
        regex=r'^roster/vcard/$',
        view=views.RosterVCardView.as_view(),
        name='roster-vcard-noargs',
    ),
    url(
        regex=r'^roster/(?P<year>\d{4})/(?P<semester>\w+)/vcard/$',
        view=views.RosterVCardView.as_view(),
        name='roster-vcard',
    ),
    url(
        regex=r'^roster/send-requirements-emails/$',
        view=views.SendRequirementsEmailsView.as_view(),
        name='send-requirements-emails',
    ),
)

shifts/urls.py
from django.conf.urls import patterns, url

from shifts import views


urlpatterns = patterns('',
    url(
        regex=r'^(?P<pk>\d+)/edit/$',
        view=views.EditShiftView.as_view(),
        name='shift-edit',
    ),
    url(
        regex=r'^(?P<pk>\d+)/delete/$',
        view=views.DeleteShiftView.as_view(),
        name='shift-delete',
    ),
    url(
        regex=r'^new/$',
        view=views.CreateShiftView.as_view(),
        name='shift-new',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/$',
        view=views.MonthView.as_view(),
        name='month',
    ),
    url(
        regex=r'^month/$',
        view=views.MonthView.as_view(),
        name='month-noargs',
    ),
)

tours/urls.py
from django.conf.urls import patterns, url

from tours import views


urlpatterns = patterns('',
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/$',
        view=views.MonthView.as_view(),
        name='month',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/print/$',
        view=views.MonthView.as_view(),
        name='month-print',
        kwargs={'print': True},
    ),
    url(
        regex=r'^month/$',
        view=views.MonthView.as_view(),
        name='month-noargs',
    ),
    url(
        regex=r'^tour/(?P<pk>\d+)/edit/$',
        view=views.EditTourView.as_view(),
        name='tour-edit',
    ),
    url(
        regex=r'^tour/(?P<pk>\d+)/delete/$',
        view=views.DeleteTourView.as_view(),
        name='tour-delete',
    ),
    url(
        regex=r'^tour/new/$',
        view=views.CreateTourView.as_view(),
        name='tour-new',
    ),
    url(
        regex=r'^default-tour/(?P<pk>\d+)/edit/$',
        view=views.EditDefaultTourView.as_view(),
        name='defaulttour-edit',
    ),
    url(
        regex=r'^default-tour/(?P<pk>\d+)/delete/$',
        view=views.DeleteDefaultTourView.as_view(),
        name='defaulttour-delete',
    ),
    url(
        regex=r'^default-tour/new/$',
        view=views.CreateDefaultTourView.as_view(),
        name='defaulttour-new',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/initialize/$',
        view=views.InitializeMonthView.as_view(),
        name='initialize-month',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/uninitialize/$',
        view=views.UninitializeMonthView.as_view(),
        name='uninitialize-month',
    ),
    url(
        regex=r'^month/initialize/$',
        view=views.InitializeMonthView.as_view(),
        name='month-initialize-noargs',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/open/$',
        view=views.CreateOpenMonthView.as_view(),
        name='open-month',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/open/edit/$',
        view=views.CreateOpenMonthView.as_view(),
        name='open-month-edit',
    ),
    url(
        regex=r'^month/(?P<year>\d{4})/(?P<month>\d{1,2})/close/$',
        view=views.CloseMonthView.as_view(),
        name='close-month',
    ),
)

urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'^', include('core.urls', namespace='core', app_name='core')),
    url(r'^tours/', include('tours.urls', namespace='tours', app_name='tours')),
    url(r'^shifts/', include('shifts.urls', namespace='shifts', app_name='shifts')),
    url(r'^profiles/', include('profiles.urls', namespace='profiles', app_name='profiles')),
    url(r'^public/', include('public.urls', namespace='public', app_name='public')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
)

profiles/models.py
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField
import vobject

from core import utils as core_utils


class PersonQuerySet(models.QuerySet):
    def inactive(self, semester=None, year=None):
        """
        Includes only members who are inactive for the given semester and year
        """
        if semester is None:
            semester = core_utils.current_semester()
        if year is None:
            year = core_utils.now().year
        else:
            year = int(year)
            semester = semester.lower()

        return self.filter(inactive_semesters__year__exact=year, inactive_semesters__semester=semester)

    def active(self, semester=None, year=None):
        """
        Excludes members who are inactive for the given semester and year
        """
        if semester is None:
            semester = core_utils.current_semester()
        if year is None:
            year = core_utils.now().year
        else:
            year = int(year)

        semester = semester.lower()

        return self.exclude(inactive_semesters__year__exact=year, inactive_semesters__semester=semester)

    def current_members(self, semester=None, year=None):
        if semester is None:
            semester = core_utils.current_semester()
        if year is None:
            year = core_utils.now().year
        else:
            year = int(year)
            semester = semester.lower()

        senior_year, freshman_year = core_utils.class_years(semester=semester, year=year, bookends_only=True)

        kwargs = {}

        if semester == 'fall':
            kwargs['member_since_year__lte'] = year
        else:
            kwargs['member_since_year__lt'] = year

        kwargs['year__lte'] = freshman_year
        kwargs['year__gte'] = senior_year

        return self.filter(**kwargs)


class Person(models.Model):
    user = models.OneToOneField('auth.User', null=True, blank=True)
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    harvard_email = models.EmailField()
    phone = PhoneNumberField()
    year = models.IntegerField(max_length=4)
    notes = models.TextField(max_length=2000, blank=True)

    titles = ['President', 'Vice President', 'Treasurer', 'Secretary', 'Tour Coordinator (Primary)', 'Tour Coordinator', 'Freshman Week Coordinator', 'Other Board Member', 'Regular Member']

    positions_choices = [(i, i) for i in titles]
    position = models.CharField(max_length=50, choices=positions_choices, default='Regular Member')
    site_admin = models.BooleanField(default=False)

    # member since fall of...
    member_since_year = models.IntegerField(max_length=4)

    houses = ('Adams', 'Quincy', 'Lowell', 'Eliot', 'Kirkland', 'Winthrop', 'Mather', 'Leverett', 'Dunster', 'Cabot', 'Pforzheimer', 'Currier', 'Dudley', 'Freshman (Yard)')
    houses_choices = [(house, house) for house in houses]
    house = models.CharField(choices=houses_choices, max_length=50, blank=True, null=True)

    # custom manager
    objects = PersonQuerySet.as_manager()

    def phone_display(self):
        """
        Removes the +1 from the phone number if it exists.
        """
        phone = unicode(self.phone)
        if phone[:2] == '+1':
            return phone[2:]
        else:
            return phone

    def requirements(self, semester=None, year=None):
        """
        Get requirements for a given semester.
        """
        year, semester = core_utils.parse_year_semester(year, semester)

        tours_required = self.tours_required_num(semester, year)
        shifts_required = self.shifts_required_num(semester, year)
        dues_required = core_utils.dues_required(semester=semester, year=year)

        return tours_required, shifts_required, dues_required

    def tours_required_num(self, semester=None, year=None):
        year, semester = core_utils.parse_year_semester(year, semester)

        # start with default
        tours_required = core_utils.get_default_num_tours(semester=semester, year=year)

        # check for override
        try:
            overridden_reqs = self.overridden_requirements.get(semester=semester, year=year)
            tours_required = overridden_reqs.tours_required
        except OverrideRequirement.DoesNotExist:
            pass

        # get number of missed tours
        num_missed = self.tours.semester(semester=semester, year=year).filter(missed=True).count()
        num_extra = num_missed * core_utils.get_setting('Missed Tour Penalty')

        return tours_required + num_extra

    def shifts_required_num(self, semester=None, year=None):
        year, semester = core_utils.parse_year_semester(year, semester)

        # start with default
        shifts_required = core_utils.get_default_num_shifts(semester=semester, year=year)

        # check for override
        try:
            overridden_reqs = self.overridden_requirements.get(semester=semester, year=year)
            shifts_required = overridden_reqs.shifts_required
        except OverrideRequirement.DoesNotExist:
            pass

        # get number of missed shifts
        num_missed = self.shifts.semester(semester=semester, year=year).filter(missed=True).count()
        num_extra = num_missed * core_utils.get_setting('Missed Shift Penalty')

        return shifts_required + num_extra

    def dues_status(self, semester=None, year=None):
        year, semester = core_utils.parse_year_semester(year, semester)
        dues_required = core_utils.dues_required(semester=semester, year=year)

        if dues_required:
            if self.dues_payments.filter(year=year, semester=semester):
                return 'complete'
            else:
                return 'incomplete'
        else:
            return 'not_required'

    def tours_status(self, semester=None, year=None):
        """
        Returns dictionary of form:
        {
            'status': 'complete'|'incomplete'|'projected',
            'num_required': int,
            'num_remaining': int,
            'num_to_sign_up': int,
            'num_extra': int,
            'date_projected': date|None,
            'complete': [],
            'late': [],
            'missed': [],
            'upcoming': [],
            'tours': [],
        }
        """
        year, semester = core_utils.parse_year_semester(year, semester)
        now_obj = core_utils.now()
        semester_tours = self.tours.filter(counts_for_requirements=True).semester(semester=semester, year=year).order_by('time')
        complete = semester_tours.filter(missed=False, time__lte=now_obj)
        late = semester_tours.filter(late=True, missed=False, time__lte=now_obj)
        missed = semester_tours.filter(missed=True, time__lte=now_obj)
        past = semester_tours.filter(time__lt=now_obj)
        upcoming = semester_tours.filter(time__gte=now_obj)

        num_required = self.tours_required_num(semester=semester, year=year)
        num_remaining = num_required - complete.count()
        num_extra = abs(min(num_remaining, 0))
        num_remaining = max(num_remaining, 0)
        num_to_sign_up = max(num_remaining - upcoming.count(), 0)

        # calculate status
        if num_remaining <= 0:
            status = 'complete'
        elif num_remaining <= upcoming.count():
            status = 'projected'
        else:
            status = 'incomplete'

        if status == 'projected':
            completion_obj = upcoming[num_remaining - 1]
            date_projected = completion_obj.time
        else:
            date_projected = None

        return {
            'status': status,
            'num_required': num_required,
            'num_remaining': num_remaining,
            'num_to_sign_up': num_to_sign_up,
            'num_extra': num_extra,
            'date_projected': date_projected,
            'complete': complete,
            'late': late,
            'missed': missed,
            'past': past,
            'upcoming': upcoming,
            'tours': semester_tours,
        }

    def shifts_status(self, semester=None, year=None):
        """
        Returns dictionary of form:
        {
            'status': 'complete'|'incomplete'|'projected',
            'num_required': int,
            'num_remaining': int,
            'num_to_sign_up': int,
            'num_extra': int,
            'date_projected': date|None,
            'complete': [],
            'late': [],
            'missed': [],
            'past': [],
            'upcoming': [],
            'shifts': [],
        }
        """
        year, semester = core_utils.parse_year_semester(year, semester)
        now_obj = core_utils.now()
        semester_shifts = self.shifts.filter(counts_for_requirements=True).semester(semester=semester, year=year).order_by('time')
        complete = semester_shifts.filter(missed=False, time__lte=now_obj)
        late = semester_shifts.filter(late=True, missed=False, time__lte=now_obj)
        missed = semester_shifts.filter(missed=True, time__lte=now_obj)
        past = semester_shifts.filter(time__lt=now_obj)
        upcoming = semester_shifts.filter(time__gte=now_obj)

        num_required = self.shifts_required_num(semester=semester, year=year)
        num_remaining = num_required - complete.count()
        num_extra = abs(min(num_remaining, 0))
        num_remaining = max(num_remaining, 0)
        num_to_sign_up = max(num_remaining - upcoming.count(), 0)

        # calculate status
        if num_remaining <= 0:
            status = 'complete'
        elif num_remaining <= upcoming.count():
            status = 'projected'
        else:
            status = 'incomplete'

        if status == 'projected':
            completion_obj = upcoming[num_remaining - 1]
            date_projected = completion_obj.time
        else:
            date_projected = None

        return {
            'status': status,
            'num_required': num_required,

shifts/models.py
import pytz

from django.db import models

from core import utils as core_utils
from tours.models import TaskQuerySet


class Shift(models.Model):
    source_choices_flat = (
        "TEACH",
        "Parents' Weekend",
        "Visitas",
        "Comp",
        "Arts First",
        "Freshman Week",
        "Other",
    )

    source_choices = [(i, i) for i in source_choices_flat]

    source = models.CharField(max_length=500)
    person = models.ForeignKey('profiles.Person', related_name='shifts', null=True, blank=True)
    time = models.DateTimeField()
    notes = models.TextField(max_length=2000, blank=True)
    missed = models.BooleanField(default=False)
    late = models.BooleanField(default=False)
    length = models.IntegerField(max_length=3, blank=True, null=True)
    counts_for_requirements = models.BooleanField(default=True)

    # custom manager
    objects = TaskQuerySet.as_manager()

    def time_local(self):
        return core_utils.localize_time(self.time)

    def is_missed(self):
        if self.missed:
            return True
        else:
            return False

    def is_late(self):
        if self.late:
            return True
        else:
            return False

    def is_unclaimed(self):
        if self.person is None:
            return True
        else:
            return False

    @property
    def is_upcoming(self):
        now = core_utils.now()
        if self.time > now:
            return True
        else:
            return False

    def __unicode__(self):
        if self.person is not None:
            return self.source + ', ' + self.time.astimezone(pytz.timezone('America/New_York')).strftime("%m/%d/%y %H:%M") + ', ' + self.person.first_name + ' ' + self.person.last_name
        else:
            return self.source + ', ' + self.time.astimezone(pytz.timezone('America/New_York')).strftime("%m/%d/%y %H:%M") + ', ' + 'Unclaimed'

templates/profiles/new_person_formset.html
{% extends "base.html" %}
{% load staticfiles core_tags %}

{% block title %} CKS Tour Management: Bulk Add New Members {% endblock %}

{% block content %}

<h1>Bulk Add New Members</h1>

{% for error in formset.non_form_errors %}
    {% render_error error|escape %}
{% endfor %}

<form class="form" id="person_form" role="form" method="post">
    {% csrf_token %}
    {{ formset.management_form }}

    <div class="row">
        <table id="formset" class="table">
        {% for form in formset.forms %}
          {% if forloop.first %}
          <thead><tr>
            {% for field in form.visible_fields %}
            <th>{{ field.label|capfirst }}</th>
            {% endfor %}
          </tr></thead>
          {% endif %}
          <tr>
          {% for field in form.visible_fields %}
            <td>
            {% if forloop.first %}
                {% for error in form.non_field_errors %}
                    {% render_error error|escape %}
                {% endfor %}
            {% endif %}

            {% for error in field.errors %}
                {% render_error error|escape %}
            {% endfor %}

            {# Include the hidden fields in the form #}
            {% if forloop.first %}
              {% for hidden in form.hidden_fields %}
              {{ hidden }}
              {% endfor %}
            {% endif %}
              {{ field }}
            </td>
          {% endfor %}
          </tr>
        {% endfor %}
        </table>
    </div>
    <div class="button_container">
        <button class="btn btn-danger">Submit</button>
    </div>
</form>

{% endblock %}

templates/profiles/requirements_emails_confirm.html
{% extends "base.html" %}
{% load staticfiles core_tags %}

{% block title %} CKS Tour Management: Send Requirements Emails {% endblock %}

{% block content %}
<h1>
    Requirements Emails Sent
</h1>
<div class="col-md-12">
    <p>Requirements update emails sent to {{ num }} members.</p>
</div>
{% endblock %}

templates/profiles/roster.html
{% extends "base.html" %}
{% load static staticfiles core_tags %}

{% block title %} CKS Tour Management: Roster {{ semester|title }} {{ year }} {% endblock %}

{% block extrahead %}
    
    <script type="text/javascript">
        $(function() {
            var showing_form = false;
            $('#toggle_requirement_status_btn').click(function()
            {
                $('.status_incomplete').toggleClass('incomplete_cell');
                $('.status_complete').toggleClass('complete_cell');
                $('.status_projected').toggleClass('projected_cell');
            });

            $('#toggle_inactive_users_btn').click(function()
            {
                $('.inactive-member').toggle();
            });

            {% if perms.profiles.add_duespayment and perms.profiles.delete_duespayment and collect_dues %}
                $('#toggle_dues_payment_form_btn').click(function()
                {
                    if (showing_form == false) {
                        showing_form = true;
                        $('.dues_payment_form').show();
                        $('#submit_dues_payment_form_btn').show();
                        $('.dues_payment_cell .requirement_circle').hide();
                    } else {
                        showing_form = false;
                        $('.dues_payment_form').hide();
                        $('#submit_dues_payment_form_btn').hide();
                        $('.dues_payment_cell .requirement_circle').show();
                    }
                });

                $('#submit_dues_payment_form_btn').click(function()
                {
                    $('form.dues-form').submit();
                });
            {% endif %}
        });
    </script>

    <script src="{% static "lib/sticky-table-headers/jquery.stickytableheaders.min.js" %}" type="text/javascript"></script>
    <script type="text/javascript">
    $(function(){
        $(".roster").stickyTableHeaders({fixedOffset: $('.navbar')});
    });
    </script>


{% endblock %}

{% block content %}
<h1>
    <a class="circle-container circle-left" href="{% url 'profiles:roster' year=prev_semester.year semester=prev_semester.semester %}">
        <div class="circle"><i class="glyphicon glyphicon-chevron-left"></i></div>
    </a>
    CKS Roster: {{ semester|title }} {{ year }}
    <a class="circle-container circle-right" href="{% url 'profiles:roster' year=next_semester.year semester=next_semester.semester %}">
        <div class="circle"><i class="glyphicon glyphicon-chevron-right"></i></div>
    </a>
</h1>

<form class='dues-form' method="post" action="./">
    {% csrf_token %}
    <table class="table table-striped table-bordered persist-area roster">

        <thead class="persist-header">
            <th>First</th>
            <th>Last</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Year</th>
            <th>House</th>
            {% if perms.profiles.change_person %}
                <th>Edit</th>
            {% endif %}
            {% if collect_dues %}
                <th>Dues</th>
            {% endif %}
            <th>Tours</th>
            <th>Shifts</th>
        </thead>

        <tbody>
            {% for person in people %}
                <tr{% if not person.cached_status.active %} class=" inactive-member"{% endif %}>
                    <td>{{ person.first_name }}</td>
                    <td>{{ person.last_name }}</td>
                    <td>{{ person.email }}</td>
                    <td>{{ person.phone_display }}</td>
                    <td>{{ person.year }}</td>
                    <td>{{ person.house }}</td>
                    {% if perms.profiles.change_person %}
                        <td class="edit"><a href="{% url 'profiles:person-edit' person.pk %}" class="edit-btn"><span class="glyphicon glyphicon-edit"></span></a></td>
                    {% endif %}

                    {% if collect_dues %}
                        <td class="dues {% if person.cached_status.active %}status_{{ person.cached_status.dues_status }}{% endif %} dues_payment_cell">
                        {% if person.cached_status.active %}

                            {% if person.cached_status.dues_status == 'complete' %}
                                <div class="requirement_circle complete"></div>
                            {% else %}
                                <div class="requirement_circle empty"></div>
                            {% endif %}
                                
                            {% if perms.profiles.add_duespayment and perms.profiles.delete_duespayment and collect_dues %}
                                <div class="dues_payment_form">
                                {{ person.dues_payment_form.pk }} {{ person.dues_payment_form.paid }}</div>
                            {% endif %}

                        {% endif %}
                        </td>
                    {% endif %}

                    <td class="tours status_{% if person.cached_status.active %}{{ person.cached_status.tours_status.status }}{% endif %}">
                        {% if person.cached_status.active %}
                            {% if person.cached_status.tours_status.status == 'incomplete' %}
                                <div class="remaining">{{ person.cached_status.tours_status.num_remaining }}</div>
                            {% elif person.cached_status.tours_status.status == 'projected' %}
                                    <div class="remaining">{{ person.cached_status.tours_status.date_projected|date:'m/d' }}</div>
                            {% else %}
                                <div class="remaining">{% if person.cached_status.tours_status.num_extra > 0 %}+{{ person.cached_status.tours_status.num_extra }}{% endif %}</div>
                            {% endif %}
                            
                            {% for tour in person.cached_status.tours_status.tours %}
                                {% if perms.tours.change_tour %}<a href="{% url 'tours:tour-edit' tour.pk %}">{% endif %}
                                    <div data-hint="{{ tour.source }} tour on {{ tour.time|date:"m/d" }}{% if tour.missed %} (missed){% elif tour.late %} (late){% elif tour.is_upcoming %} (upcoming){% endif %}" class="hint hint--top requirement_circle{% if tour.missed %} missed{% elif tour.late %} late{% elif tour.is_upcoming %} upcoming{% else %} complete{% endif %}"></div>
                                {% if perms.tours.change_tour %}</a>{% endif %}
                            {% endfor %}

                            {% for i in person.cached_status.tours_status.num_to_sign_up|get_range %}
                                <div class="requirement_circle empty"></div>
                            {% endfor %}
                        {% endif %}
                    </td>
                        
                    <td class="shifts status_{% if person.cached_status.active %}{{ person.cached_status.shifts_status.status }}{% endif %}">
                        {% if person.cached_status.active %}
                            {% if person.cached_status.shifts_status.status == 'incomplete' %}
                                <div class="remaining">{{ person.cached_status.shifts_status.num_remaining }}</div>
                            {% elif person.cached_status.shifts_status.status == 'projected' %}
                                    <div class="remaining">{{ person.cached_status.shifts_status.date_projected|date:'m/d' }}</div>
                            {% else %}
                                <div class="remaining">{% if person.cached_status.shifts_status.num_extra > 0 %}+{{ person.cached_status.shifts_status.num_extra }}{% endif %}</div>
                            {% endif %}
                            
                            {% for shift in person.cached_status.shifts_status.shifts %}
                                {% if perms.shifts.change_shift %}<a href="{% url 'shifts:shift-edit' shift.pk %}">{% endif %}
                                    <div data-hint="{{ shift.source }} shift on {{ shift.time|date:"m/d" }}{% if shift.missed %} (missed){% elif shift.late %} (late){% elif shift.is_upcoming %} (upcoming){% endif %}" class="hint hint--top requirement_circle{% if shift.missed %} missed{% elif shift.late %} late{% elif shift.is_upcoming %} upcoming{% else %} complete{% endif %}"></div>
                                {% if perms.shifts.change_shift %}</a>{% endif %}
                            {% endfor %}

                            {% for i in person.cached_status.shifts_status.num_to_sign_up|get_range %}
                                <div class="requirement_circle empty"></div>
                            {% endfor %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</form>


<div class="row">
    <div class="col-sm-6 key roster-key">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Key</h3>
            </div>

            <div class="panel-body">
                <table>
                    <tr><td><div class="requirement_circle complete"></div></td><td>Requirement Complete</td></tr>
                    <tr><td><div class="requirement_circle upcoming"></span></td><td>Requirement Projected to Complete</td></tr>
                    <tr><td><div class="requirement_circle empty"></div></td><td>Requirement Incomplete</td></tr>
                    <tr><td><div class="requirement_circle late"></div></td><td>Requirement Completed (Late)</td></tr>
                    <tr><td><div class="requirement_circle missed"></div></td><td>Requirement Missed</td></tr>
                </table>
            </div>
        </div>
    </div>

    <div class="col-sm-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Actions</h3>
            </div>
            <div class="panel-body">
                <a id="toggle_requirement_status_btn" class="btn btn-danger btn-block">Toggle Requirement Status</a>
                <a id="toggle_inactive_users_btn" class="btn btn-danger btn-block">Toggle Inactive Members</a>
                <a href="{% url 'profiles:roster-vcard' semester=semester year=year %}" class="btn btn-danger btn-block">Download V-Card</a>
                {% if perms.profiles.add_duespayment and perms.profiles.delete_duespayment and collect_dues %}
                    <a id="toggle_dues_payment_form_btn" class="btn btn-danger btn-block">Toggle Dues Payment Form</a>
                    <button id="submit_dues_payment_form_btn" class="btn btn-info btn-block">Submit</button>
                {% endif %}
                {% if perms.profiles.send_requirements_email and is_current_semester %}
                    <a href="{% url 'profiles:send-requirements-emails' %}" data-action="send requirements update emails to all active members" class="btn btn-danger btn-block post-btn">Send Requirements Update Emails</a>
                {% endif %}
            </div>
        </div>
    </div>

</div><!-- /.row -->
{% endblock %}